server:
  port: 8090
around:
  hub:
    short:
      url:
        id: '"E1KSH4XDjVDAVGHNjVzm";'
        secret: '"0GWzpWTm_I";'
spring:
  redis:
    host: localhost
    port: '6379'
  application:
    name: springboot
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    password: ENC(n1EF6di0hk+MxXUlo9T1cA==)
    username: ENC(80s5/ObtRtZpmX2VhJXx3Q==)
    url: jdbc:mariadb://localhost:3306/shop
  profiles:
    active: old
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
  config:
    use-legacy-processing: 'true'
studio:
  thinkground:
    loading:
      message: "@@ runrunrun old environment @@"
jasypt:
  encryptor:
    bean: jasyptStringEncryptor


    springdoc:
      swagger-ui:
        path=/swagger-ui.html
#springdoc:
#  api-docs:
#    path: /api-docs
#  default-consumes-media-type: application/json
#  default-produces-media-type: application/json
#  swagger-ui:
#    enabled: true
#    operations-sorter: alpha
#    tags-sorter: alpha
#    path: /swagger-ui.html
#    disable-swagger-default-url: true
#    display-query-params-without-oauth2: true
#    doc-expansion: none
#  paths-to-match:
#    - /api/**
